name: 'Dependency Review'

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.7.2
        with:
          # fail if a pull request introduce vulnerabilities of level "low" or higher
          fail-on-severity: low
          # allowed licenses in SPDX format, the action will fail if a new dependencies with a license not in this list is introduced
          # if the license cant be detected, the action will inform but not fail
          allow-licenses: 'Apache-2.0, MIT, GPL-3.0-or-later, MPL-2.0, BSD-3-Clause, BSD-2-Clause'
          # threshold for the OpenSSF Scorecard level, the action will get a warning in the CI
          warn-on-openssf-scorecard-level: 3
